name: Build & Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - .github/**
      - '!.github/workflows/build-test.yml'
  pull_request:
  merge_group:
    branches:
      - main
    paths-ignore:
      - README.md
      - .github/**
      - '!.github/workflows/build-test.yml'

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Rush Install
        run: node common/scripts/install-run-rush.js install
      - name: Run tests
        run: cd tests/unit && rushx test
