name: Build & Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - .github/**
      - '!.github/workflows/build-test.yml'
  pull_request:
  merge_group:
    branches:
      - main
    paths-ignore:
      - README.md
      - .github/**
      - '!.github/workflows/build-test.yml'

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Rush Install
        run: node common/scripts/install-run-rush.js install
      - name: Run Tests
        run: node ../../common/scripts/install-run-rushx.js test
        working-directory: tests/unit

  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Rush Install
        run: node common/scripts/install-run-rush.js install
      - name: Run Tests
        run: node ../../common/scripts/install-run-rushx.js test
        working-directory: tests/integration

  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Rush Install
        run: node common/scripts/install-run-rush.js install
      - name: Compile
        run: node common/scripts/install-run-rush.js compile
