name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Git config user
        uses: snow-actions/git-config-user@v1.0.0
        with:
          name: himself65
          email: himself65@outlook.com
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Verify Change Logs
        run: node common/scripts/install-run-rush.cjs change --verify
      - name: Rush Install
        run: node common/scripts/install-run-rush.cjs install
      - name: Rush rebuild
        run: node common/scripts/install-run-rush.cjs rebuild --verbose --production
